### ISSUE TITLE
Internet Explorer 11 support

### ISSUE THREAD

**Issue by hybridvision** [mladenilic/columns.js#2]
Hi @mladenilic,

Thank you for this neat library! I needed to have IE11 support and in the end I was able to get it to work quite easily by adding some polyfills. I thought I would post what I added for reference in case anyone else needs to do the same.

The polyfills come from https://polyfill.io/v3/url-builder/ and this is what I included in my site:

* NodeList.prototype.forEach
* Object.assign
* Array.from
* Object.entries
* Element.prototype.append

They can be added via a single `<script>` tag:

```html
<script src="https://polyfill.io/v3/polyfill.min.js?features=NodeList.prototype.forEach%2CObject.assign%2CArray.from%2CObject.entries%2CElement.prototype.append"></script>
```

I hope this helps someone!

**Comment by mladenilic** [comment]
@hybridvision Thanks a lot for the issue. 💪

Latest release uses object spread syntax instead of Object.assign, so that polyfill should no longer be needed. I've also added IE support info to the readme file.
